"""empty message

Revision ID: 7a3972e30eed
Revises: 51f5ccfba190
Create Date: 2016-06-08 10:39:12.648102

"""

# revision identifiers, used by Alembic.
revision = '7a3972e30eed'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
