"""empty message

Revision ID: be1668e30124
Revises: 7a3972e30eed
Create Date: 2016-06-17 15:45:24.321530

"""

# revision identifiers, used by Alembic.
revision = 'be1668e30124'
down_revision = '7a3972e30eed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    ### end Alembic commands ###
